id: PFB155615
initial_creation_type: ocr
source_metadata:
  volumes:
    315163a476214c559052c1b675bb06d8:
      base_file: v076.txt
      image_group_id: I1PD95921
      title: ཐེག་པ་ཆེན་པོ་བསྡུས་པ།
      total_pages: 1774
      volume_number: 76
